[package]
name = "save_for_reading"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
rand = "0.8.5"
reqwest = { version = "0.11.16", features = ["blocking"] }
